# -*- coding: utf-8 -*-
"""EstruturasDeRepeticaoFor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ojO0wT4iPZRQlpxkiMtCYbDRYGuG5aV6

1. Faça um programa que leia 5 números e informe o maior número.
"""

maior_numero = float('-inf')

for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  if numero > maior_numero:
    maior_numero = numero

  print(f"O maior numero digitado é: {maior_numero}")

"""2. Faça um programa que verifique e mostre os números entre 1.000 e 2.000
(inclusive) que, quando divididos por 11 produzam resto igual a 2.

"""

for numero in range(1000, 2001):
    if numero % 11 == 2:
        print(numero)

"""3. Faça um programa que leia 5 números e informe a soma e a média dos
números.

"""

sona = 0
for i in range(1,5):
  n=float(input(f"Digite o {i}º número "))
  sona += n
  media = sona/i

print(f"Soma = {sona}, média = {media}")

"""4. Faça um programa que receba um número e usando laços de repetição
calcule e mostre a tabuada desse número.

"""

numero = int(input("Digite um número para ver sua tabuada: "))

print(f"Tabuada de {numero}:")
for i in range(1, 11):
    resultado = numero * i
    print(f"{numero} x {i} = {resultado}")

"""5. Faça um programa que mostre as tabuadas dos números de 1 a 10 usando
laços de repetição.

"""

for i in range(1, 11):
  print(f"Tabuada de {i}:")
  for t in range (1,11):
    resultado = i * t
    print(f"{t} x {i} = {resultado}")

"""6. Faça um programa que imprima na tela os números de 1 a 20, um abaixo
do outro. Depois modifique o programa para que ele mostre os números
um ao lado do outro.

"""

for i in range(1,21):
  print(i)

print(list(range(1,21)))

"""7. Faça um programa que imprima na tela apenas os números ímpares entre
1 e 50.
"""

for i in range(1,51):
  if i%2!=0:
    print(i)

"""8. Faça um programa que receba dois números inteiros e gere os números
inteiros que estão no intervalo compreendido por eles.

"""

min = int(input("Informe o limite mínimo: "))
max = int(input("Informe o limite máximo: "))
for i in range(min+1, max):
  print(i)

"""9. Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi
superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor
mostre na tela uma mensagem contendo em quanto foi superado o
faturamento.

"""

acum = 0
for i in range(1,6):
  acum += float(input(f"Informe o valor do faturamento do {i}º cliente: "))
if(acum > 54000):
  print(f"Valor superado foi de {acum-54000} ")

"""10. Faça um programa que peça 10 números inteiros, calcule e mostre a
quantidade de números pares e a quantidade de números impares.
"""

qtd_par = 0
qtd_impar = 0
for i in range(1,11):
  num=int(input(f"Informe o {i}º número: "))
  if num%2==0:
    qtd_par +=1
  else:
    qtd_impar +=1

print(f"Quantidade de números pares é de: {qtd_par} e a quantidade de números ímpares é de: {qtd_impar}. ")

"""11. Um funcionário de uma empresa recebe aumento salarial anualmente:
Sabe-se que:
Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao
dobro do percentual do ano anterior. Faça um programa que determine o
salário atual desse funcionário. Após concluir isto, altere o programa
permitindo que o usuário digite o salário inicial do funcionário.
"""

sal= float(input("Informe o salário inicial: "))
aum = 0.015
for i in range (1997,2025):
  aum *=2
  sal += sal*aum
print(f"Salário atual do funcionário é de: {sal}  ")

"""12. Faça um programa que peça uma nota, entre zero e dez. Mostre uma
mensagem caso o valor seja inválido e continue pedindo até que o usuário
informe um valor válido.
"""

for i in range(1000):
  num=int(input("Informe a nota válida de 1 a 10: "))
  if num in range(11):
    print(f"Número informado é válido")
    break
  else:
    print("Nota Inválida por favor entre um valor de 0 a 10")

"""13. Uma loja tem tem uma política de descontos de acordo com o valor da
compra do cliente. Os descontos começam acima dos R$500. A cada 100
reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até
25%.
Por exemplo: R$500 = 1% || R$600,00 = 2% … etc…
Faça um programa que exiba essa tabela de descontos no seguinte formato:
Valordacompra – porcentagem de desconto – valor final

"""

desc = 0.01
valor_gasto = int(input("Informe o valor gasto: "))
if (valor_gasto <=500):
  print("Valor abaixo do mínimo para desconto")
else:
  for i in range(500,valor_gasto,100):
    if (desc <=0.25):
       print(f"Valor da compra: {i} Desconto: {round(desc * 100,2)}% Valor final: {i-(i*desc)} ")
       desc += 0.01
    else:
      print(f"Valor da compra: {i} Desconto: 25 % Valor final: {i-(i*0.25)} ")

"""14. Faça um programa que receba a idade de 15 pessoas e que calcule e
mostre:
* a) A quantidade de pessoas em cada faixa etária;
* b) A percentagem de pessoas na primeira e na última faixa etária, com relação
ao total de pessoas:
* Até 15 anos
* De 16 a 30 anos
* De 31 a 45 anos
* De 46 a 60 anos
* Acima de 61 anos
"""

f15 = 0
f16_30 = 0
f31_45 = 0
f46_60 = 0
f61 = 0
for i in range(15):
  idade = int(input(f"Informe a {i+1}º idade: "))
  if (idade > 60):
    f61 +=1
  elif (idade > 45):
    f46_60 +=1
  elif (idade > 30):
    f31_45 +=1
  elif (idade >15):
    f16_30 +=1
  else:
    f15 += 1
print(f"Qtd pessoas até 15 anos: {f15} que corresponde: {round((f15/(f15+f16_30+f31_45+f46_60+f61))*100,2)}% do total de pessoas")
print(f"Qtd de pessoas de 16 a 30 anos:{f16_30}")
print(f"Qtd de pessoas de 31 a 45 anos:{f31_45}")
print(f"Qtd de pessoas de 46 a 60 anos:{f46_60}")
print(f"Qtd de pessoas de acima de 61 anos:{f61} que corresponde: {round((f61/(f15+f16_30+f31_45+f46_60+f61))*100,2)}% do total de pessoas")

"""15. Faça um programa que peça dois números, base e expoente, calcule e
mostre o primeiro número elevado ao segundo número. Não utilize a
função de potência da linguagem.

"""

res = 1
base = int(input("Informe a base: "))
exp = int(input("Informe o expoente: "))
if (exp == 0):
  print(f"{base} elevado a {exp} =  1")
else:
  for i in range (1,exp+1):
    res = res * base
  print(f"{base} elevado a {exp} = {res}")

"""16. Faça um programa que mostre todos os primos entre 1 e N sendo N um
número inteiro fornecido pelo usuário. O programa deverá mostrar também
o número de divisões que ele executou para encontrar os números primos.
Serão avaliados o funcionamento, o estilo e o número de testes (divisões)
executados.
"""

acum_test = 0
i = 16
for j in range(2, i+1):
  if i %j == 0:
    acum_test +=1
    if acum_test > 1:
      print("Não é numero primo")
      j = i + 1
      acum_test = 0
if(acum_test==2):
    print(f"{i}")